[package]
name = "hermes_pdf_shift_http"
version = "0.1.0"
edition = "2021"

[dependencies]
qpdf = "0.2.0"
actix-web = "4.0"
lopdf = "0.35"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
lazy_static = "1.4"
